name: Run Composition
description: Run Composition
inputs:
  backend_endpoint:
    description: 'api endpoint for the testground runner'
    required: true
    default: 'https://ci.testground.ipfs.team'
  plan_directory:
    description: 'testplan path relative'
    required: true
  composition_file:
    description: 'composition file path'
    required: true
outputs:
  status:
    description: 'status of the testground run, i.e. completed/cancled'
    value: ${{ steps.run.outputs.status }}
  outcome:
    description: 'high-level result of the test'
    value: ${{ steps.run.outputs.outcome }}
  testground_id:
    description: 'testground identifier'
    value: ${{ steps.run.outputs.testground_id }}
runs:
  using: composite
  steps:
    - run: "${{ github.action_path }}/run.sh"
      id: run
      shell: bash
      env:
        # Note: required because "Each input variable in the composite action is only viewable in its own scope."
        # https://github.com/actions/runner/issues/665
        # https://github.com/actions/runner/blob/main/docs/adrs/0549-composite-run-steps.md#inputs
        INPUT_BACKEND_ENDPOINT: ${{ inputs.backend_endpoint }}
        INPUT_PLAN_DIRECTORY: ${{ inputs.plan_directory }}
        INPUT_COMPOSITION_FILE: ${{ inputs.composition_file }}